apiVersion: apps/v1
kind: Deployment
metadata:
  name: newnginx-deployment
spec:
  selector:
   matchLabels:
     app: newnginx
  replicas: 2
  template:
    metadata: 
      labels:
        app: newnginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80       